using System;
using System.Collections.Generic;
using WarGame.Shared;

namespace WarGame.Server
{
    // Mostly generated by AI
    internal class RandomDealStrategy : IDealStrategy
    {
        public void Deal(List<CardRank> playerHand, List<CardRank> opponentHand)
        {
            var deck = new List<CardRank>();

            foreach (CardRank rank in Enum.GetValues(typeof(CardRank)))
                for (var i = 0; i < 4; i++)
                    deck.Add(rank);

            deck.Shuffle();

            for (var i = 0; i < deck.Count; i++)
                if (i % 2 == 0) playerHand.Add(deck[i]);
                else opponentHand.Add(deck[i]);
        }

        public void Shuffle(List<CardRank> list, int reshuffleNumber)
        {
            list.Shuffle();
        }
    }
}