using System;
using Cysharp.Threading.Tasks;
using DG.Tweening;
using UnityEngine;
using UnityEngine.SceneManagement;
using WarGame.Client.Animation;
using WarGame.Shared;

namespace WarGame.Client.Views
{
    // Mostly generated by AI
    public class GameController : IDisposable
    {
        private readonly GameBoard _board;
        private readonly GameClient _client;
        private readonly InputManager _inputManager;
        private readonly AnimationConfig _animationConfig;

        private bool _isProcessingRound;
        private bool _isGameFinished;

        public GameController(GameBoard board, GameClient client, InputManager inputManager, AnimationConfig animationConfig)
        {
            _board = board;
            _client = client;
            _inputManager = inputManager;
            _animationConfig = animationConfig;
        }

        public void Initialize()
        {
            _inputManager.OnInput += OnAnyInput;
        }

        public void Dispose()
        {
            _inputManager.OnInput -= OnAnyInput;
        }

        private void OnAnyInput()
        {
            // Fastest way to restart the game
            // TODO write a proper restart logic
            if (_isGameFinished)
            {
                Debug.Log($"Restarting the game");
                SceneManager.LoadScene(0);
                return;
            }

            if (_isProcessingRound) return;

            PlayRoundAsync().Forget();
        }

        private async UniTaskVoid PlayRoundAsync()
        {
            _isProcessingRound = true;
            _inputManager.DisableInput();

            var response = await _client.PlayRoundAsync();

            if (response.Status != ResponseStatus.Success)
            {
                Debug.LogError($"[Server] {response.ErrorMessage}");
                FinishRound();
                return;
            }

            if (response.EarlyGameOver)
            {
                EndGame(response.FinalResult);
                return;
            }

            await Reshuffle(response);
            await MoveCardsToWarPosition(response);
            await CompareCards(response);

            if (response.RoundResult == CompareResult.Tie)
            {
                FinishRound();
                return;
            }

            await CollectCards(response);

            if (response.IsGameOver)
            {
                EndGame(response.FinalResult);
                return;
            }

            FinishRound();
        }

        private UniTask Reshuffle(PlayRoundResponse response)
        {
            var reshuffleAnimation = DOTween.Sequence();

            if (response.PlayerHandReshuffled)
                reshuffleAnimation.Join(AnimateReshuffle(_board.PlayerCapturedCards, _board.PlayerHand));

            if (response.OpponentHandReshuffled)
                reshuffleAnimation.Join(AnimateReshuffle(_board.OpponentCapturedCards, _board.OpponentHand));

            return reshuffleAnimation.ToUniTask();
        }

        private UniTask MoveCardsToWarPosition(PlayRoundResponse response)
        {
            if (response.PlayerWarCardsPlayed <= 0)
                return UniTask.CompletedTask;

            var warSeq = DOTween.Sequence();

            for (var i = 0; i < response.PlayerWarCardsPlayed; i++)
                warSeq.Append(_board.GameBattleArea.AddCardToWarSlot(_board.PlayerHand.TakeTopCard()));

            for (var i = 0; i < response.OpponentWarCardsPlayed; i++)
                warSeq.Append(_board.GameBattleArea.AddCardToWarSlot(_board.OpponentHand.TakeTopCard()));

            return warSeq.ToUniTask();
        }

        private async UniTask CompareCards(PlayRoundResponse response)
        {
            var pCard = _board.PlayerHand.TakeTopCard();
            var oCard = _board.OpponentHand.TakeTopCard();

            await DOTween.Sequence()
                         .Join(_board.GameBattleArea.AddCardToPlayerSlot(pCard))
                         .Join(_board.GameBattleArea.AddCardToOpponentSlot(oCard))
                         .ToUniTask();

            await DOTween.Sequence()
                         .Join(pCard.Reveal(response.PlayerCard))
                         .Join(oCard.Reveal(response.OpponentCard))
                         .ToUniTask();

            await UniTask.Delay(_animationConfig.RevealResultDelayMs);
        }

        private UniTask CollectCards(PlayRoundResponse response)
        {
            var winnerPile = response.RoundResult == CompareResult.PlayerWins
                ? _board.PlayerCapturedCards
                : _board.OpponentCapturedCards;

            var tableCards = _board.GameBattleArea.TakeAllCards();
            var collectSeq = DOTween.Sequence();

            foreach (var card in tableCards)
            {
                card.Initialize(null, false);
                collectSeq.Join(winnerPile.AddCard(card, _animationConfig.CollectCardsDuration));
            }

            return collectSeq.ToUniTask();
        }

        private Sequence AnimateReshuffle(CardsContainerView from, CardsContainerView to)
        {
            var sequence = DOTween.Sequence();
            var cards = from.TakeAllCards();
            cards.Shuffle();

            foreach (var card in cards)
            {
                card.Initialize(null, false);
                sequence.Append(to.AddCard(card, _animationConfig.ReshuffleDuration));
            }

            return sequence;
        }

        private void FinishRound()
        {
            _isProcessingRound = false;
            _inputManager.EnableInput();
        }

        private void EndGame(GameResult result)
        {
            Debug.Log($"Game over: {result}");
            // TODO: show game-over UI
            _isGameFinished = true;
            _inputManager.EnableInput();
        }
    }
}